### ISSUE TITLE
Resources directory with link instead of actual file

### ISSUE THREAD

**Issue by jlconlin** [njoy/metaconfigure#17]
If a `resources` directory is found inside a `test` directory, all the files in `resources` are copied during `cmake` invocation. However, if the file in `resources` is a link, it is not copied correctly; that is, the link is copied directly, but it no longer points to the correct thing. 

This would be useful so we can use the same file for multiple tests without having to have multiple copies lying around.

**Comment by apmccartney** [comment]
Symbolic links should not be version-controlled and do not belong in the resources directory.

**Comment by jlconlin** [comment]
Well, I'm not sure I agree. If I'm reading in the same file in tests located in different directories, I'd rather not have multiple copies of the file. Is there a top-level resources directory that could be used?
